export const API_ENDPOINTS = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  LOGOUT: "/auth/logout",
  REFRESH_TOKEN: "/auth/refresh-token",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  GET_USER_PROFILE: "/user/profile",
  UPDATE_USER_PROFILE: "/user/profile/update",
  UPLOAD_AVATAR: "/user/profile/avatar",
  CHANGE_PASSWORD: "/profile/change-password",
  GET_SERVICES: "/services",
  GET_SERVICE_PROVIDERS: "/services/providers",
  BOOK_SERVICE: "/services/book",
  GET_BOOKINGS: "/services/bookings",
  CANCEL_BOOKING: "/services/bookings/cancel",
  GET_NOTIFICATIONS: "/notifications",
  MARK_NOTIFICATION_READ: "/notifications/read",
  GET_REVIEWS: "/reviews",
  SUBMIT_REVIEW: "/reviews/submit",
  GET_SETTINGS: "/settings",
  UPDATE_SETTINGS: "/settings/update",
  GET_LOCATIONS: "/locations",
  VERIFY_OTP: "/otp/email_verify",
  RESEND_OTP: "/otp/resend",
  UPLOAD: "/upload/documents",
  VERIFY_DOC:"/auth/upload-doc",
  PREFERENCES: "/auth/preferences",
  ADD_ACCOUNT: "/auth//upload-acc-details",
  ADD_BULK_WORKING_HOURS: "/sp_schedule/providers/working-hours/bulk",
  UPDATE_PREFERENCES: "/auth/update-preferences",
  GET_USER_PREFERENCES: "/auth/get-user-preferences",
  ADD_BUSINESS_INFO: "/auth/add-business-info",
  GET_BUSINESS_INFO: "/auth/get-business-info",
  UPDATE_BUSINESS_INFO: "/auth/update-business-info",
};