export const publicRoutes = [
  "/",
  "/blogs",
  "/blog/:id",
  "/about",
  "/contactUs",
  "/privacyPolicy",
  "/termsConditions",
  "/myAccount/FAQ",
//   "/help-support",
  "/search",
  "/:username",
  "/careers",
  "/cookie-policy",
  "/cus/serviceList",
  "/map",
  "/services/:id",
  "/store",
  "supplier/register",
  "/cus/servicesList",
  "/supplier/register",
];
