export interface Address {
    id: string,
    user_id: string,
    address_name: string,
    building_no: string | null,
    floor: string | null,
    address: string,
    landmark: string | null,
    pincode: string,
    city_town: string,
    state: string,
    country: string,
    is_default: boolean,
    created_at: string,
    updated_at: string,
    deleted_at: string | null,
    is_deleted: boolean,
    latitude: number,
    longitude: number
}
